In [1]:
import pandas as pd

# Basically their are two type of data in pandas 
1. series (1D)
2. DataFrame (2D)

For the series

In [2]:
cars=pd.Series(["BMW","Mercedes","Porsche"])
cars

0         BMW
1    Mercedes
2     Porsche
dtype: object

In [3]:
color=pd.Series(["Grey","Black","Golden","Red"])
color

0      Grey
1     Black
2    Golden
3       Red
dtype: object

For the dataFrame

In [4]:
dataframe=pd.DataFrame({"Cars":cars,"Color":color})

In [5]:
dataframe

       Cars   Color
0       BMW    Grey
1  Mercedes   Black
2   Porsche  Golden
3       NaN     Red

In [6]:
cars[3]="Kabin"

In [7]:
cars

0         BMW
1    Mercedes
2     Porsche
3       Kabin
dtype: object

In [12]:
students=(["kabin","Sushnat","Remon","Aayush"])

In [13]:
roll=([1,2,3,4,])

In [14]:
roll

[1, 2, 3, 4]

In [15]:
att=pd.DataFrame({
    "Name":students,
    "Roll":roll
})

In [16]:
att

      Name  Roll
0    kabin     1
1  Sushnat     2
2    Remon     3
3   Aayush     4